#!/usr/bin/env python
from __future__ import print_function
from orgtools import *
from glob import glob
from xastools.xas import file2spectrum
from os.path import join, basename
import sys
import argparse

import matplotlib.pyplot as plt

plt.ion()

parser = argparse.ArgumentParser()
parser.add_argument('filename')

args = parser.parse_args()
filename = args.filename
x = file2spectrum(filename)
print(x.cols)